name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
            
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outpts.version }}
        echo "New version: $NEW_VERSION!!!!!!!!!!!"

#    - name: Build Docker Image
#      run: |
#        docker build -t 98251998/docker-graphql:0.0.2 .
#        docker build -t 98251998/docker-graphql:latest .

#    - name: Push Docker Image
#      run: |
#        docker push 98251998/docker-graphql:0.0.2
#        docker push 98251998/docker-graphql:latest
